### RUN
# ./burl-cli -f "specs.toml" from-toml

###--- REQUIRED PARAMS ----

# url = "http://127.0.0.1:8000/ping" # fastapi
# url = "http://127.0.0.1:8000/delayed/10" # fastapi
url = "http://127.0.0.1:8000/items" # fastapi post

## --- GET
# method = "Get"
## --- POST
method = "Post"
json_payload = """ { "name": "john doezer", "price": 10.2 }"""
# json_payload_ref = "json_payload.json"
# gql_query = "query {}"
### --- OPTIONAL PARAMS ----
## Auth
# bearer_token = "1q2asdasd.asdasdasd.asd123e"
## Run config
n_runs = 300                              # default=300
n_warmup_runs = 500                       # default=0
concurrency_level = 4                     # default=1
duration_scale = "Micro"                  # Secs | Milli | Micro(Default) | Nano 
report_directory = "examples/fastapi/report"

headers = [
    [
        "Content-Type",
        "application/json",
        # "application/json; charset=UTF-8",
    ],
    # [
    #     "content-encoding",
    #     "deflate, gzip",
    # ],
]

# [[headers]]
# content_type = "application/json; charset=UTF-8"
# content-encoding = "deflate, gzip"
