### RUN
# ./burl-cli -f "specs.toml" from-toml

###--- REQUIRED PARAMS ----

# url = "http://0.0.0.0:8080/ping" # actix
# url = "http://localhost:8080/ping" # actix windows
# url = "http://0.0.0.0:8080/delayed/10" # actix
# url = "http://0.0.0.0:8080/items/" # actix
# url = "http://0.0.0.0:8080/items/" # actix post
url = "http://localhost:8080/items/" # actix post windows

## --- GET
# method = "Get"
## --- POST
method = "Post"
json_payload = """{ "name": "john doezer", "price": 10.2 }"""
# json_payload_ref = "json_payload.json"
# gql_query = "query {}"
### --- OPTIONAL PARAMS ----
## Auth
# bearer_token = "1q2asdasd.asdasdasd.asd123e"
## Run config
n_runs = 300                            # default=300
n_warmup_runs = 500                     # default=0
concurrency_level = 4                   # default=1
duration_scale = "Micro"                # Secs | Milli | Micro(Default) | Nano 
report_directory = "examples/actix/report"
baseline_path = "examples/actix/report/data"
# baseline_path = "examples/fastapi/report/data"

headers = [
    [
        "Content-Type",
        "application/json"
    ],
    # [
    #     "content-encoding",
    #     "deflate, gzip",
    # ],
]

# [[headers]]
# content_type = "application/json; charset=UTF-8"
# content-encoding = "deflate, gzip"

[stats_config]
# n_bootstrap_draw_size = 100
alpha = 0.05
# n_bootstrap_samples  = 1000